server {
    listen          443;
    server_name     *.dev;
    root            /var/www/$host/web;

    ssl                         on;
    ssl_certificate             /usr/share/nginx/certs/server.crt;
    ssl_certificate_key         /usr/share/nginx/certs/server.key;
    ssl_session_timeout         5m;
    ssl_session_cache           shared:ssl_cache:5m;
    ssl_prefer_server_ciphers   on;
    ssl_protocols               SSLv2 SSLv3 TLSv1;
    ssl_ciphers                 HIGH:!aNULL:!MD5;
    
    error_log /var/log/nginx/symfony2.error.log;
    access_log /var/log/nginx/symfony2.access.log;

    # strip app.php/ prefix if it is present
    rewrite ^/app\.php/?(.*)$ /$1 permanent;

    location / {
        index app.php;
        try_files $uri @rewriteapp;
    }

    location @rewriteapp {
        rewrite ^(.*)$ /app.php/$1 last;
    }

    # pass the PHP scripts to FastCGI server from upstream phpfcgi
    # location ~ \.php$ {
    location ~ ^/(app|app_dev|config)\.php(/|$) {
        fastcgi_pass    unix:/var/run/php5-fpm.sock;
        fastcgi_split_path_info ^(.+\.php)(/.*)$;
        fastcgi_param   SCRIPT_FILENAME  $document_root$fastcgi_script_name;
        fastcgi_param   HTTPS on; 
        include         fastcgi_params;
    }
}
